source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KeyboardWrapper_Example', :exclusive => true do
  pod "KeyboardWrapper", :path => "../"
end

target 'KeyboardWrapper_Tests', :exclusive => true do
  pod "KeyboardWrapper", :path => "../"

  
end
